services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile
    ports:
     - "8000:8000"
    depends_on:
      - catalogdb
    environment:
    - ASPNETCORE_URLS=http://+:8000
    - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
    - DatabaseSettings__DatabaseName=CatalogDb
    - DatabaseSettings__ProductsCollection=Products
    - DatabaseSettings__BrandsCollection=Brands
    - DatabaseSettings__TypesCollection=Types

  catalogdb:
    image: mongo
    ports:
      - "27017:27017"            
    volumes:
      - catalogdb:/data/db
  
  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    image: postgres:13-alpine
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password1@
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U admin -d DiscountDb"]
        interval: 10s
        timeout: 5s
        retries: 5 


  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderdb
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "Marco111@"
        MSSQL_PID: "Developer" 
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - orderdb_data:/var/opt/mssql
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Marco111@' -C -Q 'SELECT 1'"]
        interval: 10s
        timeout: 5s
        retries: 10

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@ecommerc.com
        - PGADMIN_DEFAULT_PASSWORD=Password1@


      ports:
          - "5050:80"
      depends_on:
          - discountdb
      volumes:
          - pgadmin_data:/root/.pgadmin

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/Basket/Basket.API/Dockerfile
    ports:
     - "8001:8000"
    depends_on:
      - basketdb
    environment:
    - ASPNETCORE_URLS=http://+:8000
    - CacheSettings__ConnectionString=basketdb:6379
    - "GrpcSettings__DiscountUrl=http://discount.api:8080"
    
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
     - "9443:9443"
    volumes:
      - portainer_data:/data

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: services/Discount/Discount.API/Dockerfile
    container_name: discount.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - DatabaseSettings__ConnectionString=Host=discountdb;Port=5432;Database=DiscountDb;Username=admin;Password=Password1@;Pooling=true

    depends_on:
       discountdb:
         condition: service_healthy
    ports:
       - "8002:8000"

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: services/Ordering/Ordering.API/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - ConnectionStrings__OrderConnectionString=Server=orderdb,1433;Database=OrderDb;User Id=sa;Password=Marco111@;Encrypt=False;TrustServerCertificate=True;

    depends_on:
       - orderdb
    ports:
      - "8003:8000"
volumes:
  catalogdb:
  portainer_data:
  postgres_data:
  pgadmin_data:
  orderdb_data:
