services:
  reverseproxy:
    container_name: nginxgateway
    restart: always
    build:
      context: .
      dockerfile: APIGateway/nginx/nginx.Dockerfile
    depends_on:
      - identityserver
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "44344:443" 
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile
    ports:
     - "8000:8000"
    depends_on:
      - catalogdb
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
    - ASPNETCORE_URLS=http://+:8000
    - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
    - DatabaseSettings__DatabaseName=CatalogDb
    - DatabaseSettings__ProductsCollection=Products
    - DatabaseSettings__BrandsCollection=Brands
    - DatabaseSettings__TypesCollection=Types
    - "ElasticCongiuration__Uri=http://elasticsearch:9200"
    - Auth__Authority="http://host.docker.internal:9009"
    - Auth__RequireHttpsMetadata=false
    - Auth__Audience=Catalog
  catalogdb:
    image: mongo
    ports:
      - "27017:27017"            
    volumes:
      - catalogdb:/data/db
  
  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    image: postgres:13-alpine
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password1@
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U admin -d DiscountDb"]
        interval: 10s
        timeout: 5s
        retries: 5 

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderdb
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "Marco111@"
        MSSQL_PID: "Developer" 
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - orderdb_data:/var/opt/mssql
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Marco111@' -C -Q 'SELECT 1'"]
        interval: 10s
        timeout: 5s
        retries: 10
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
      image: docker.elastic.co/kibana/kibana:8.14.3
      container_name: kibana
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      depends_on:
        - elasticsearch
      ports:
        - "5601:5601"
 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
     - "5672:5672"
     - "15672:15672"

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@ecommerc.com
        - PGADMIN_DEFAULT_PASSWORD=Password1@
      ports:
          - "5050:80"
      depends_on:
          - discountdb
      volumes:
          - pgadmin_data:/root/.pgadmin

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/Basket/Basket.API/Dockerfile
    ports:
     - "8001:8000"
    depends_on:
      - basketdb
      - rabbitmq
    environment:
    - ASPNETCORE_URLS=http://+:8000
    - CacheSettings__ConnectionString=basketdb:6379
    - "GrpcSettings__DiscountUrl=http://discount.api:8080"
    - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    - "ElasticCongiuration__Uri=http://elasticsearch:9200"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
     - "9443:9443"
    volumes:
      - portainer_data:/data

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: services/Discount/Discount.API/Dockerfile
    container_name: discount.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - DatabaseSettings__ConnectionString=Host=discountdb;Port=5432;Database=DiscountDb;Username=admin;Password=Password1@;Pooling=true
        - "ElasticCongiuration__Uri=http://elasticsearch:9200"
    depends_on:
       discountdb:
         condition: service_healthy
    ports:
       - "8002:8000"

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: services/Ordering/Ordering.API/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - ConnectionStrings__OrderConnectionString=Server=orderdb,1433;Database=OrderDb;User Id=sa;Password=Marco111@;Encrypt=False;TrustServerCertificate=True;
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticCongiuration__Uri=http://elasticsearch:9200"

    depends_on:
       - orderdb
    ports:
      - "8003:8000"

  ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: APIGateway/Ocelot.ApiGateway/Ocelot.ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - identityserver
      - ordering.api
      - discount.api
      - basket.api
      - catalog.api
    ports:
      - "8010:8080"

  identityserver:
    image: ${DOCKER_REGISTRY-}eshopidentity
    container_name: IdentityServer
    environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:9011
    build:
      context: .
      dockerfile: Infrstructure/eShop.Identity/Dockerfile
    ports:
      - "9009:9009"

volumes:
  catalogdb:
  portainer_data:
  postgres_data:
  pgadmin_data:
  orderdb_data:
  elasticsearch-data:


